// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSu_5ZWmX4324trGU33rfUvA9jfDaQKh8',
    appId: '1:916915644318:android:32e501929083a76da8588f',
    messagingSenderId: '916915644318',
    projectId: 'ecommerce-app-3efdd',
    storageBucket: 'ecommerce-app-3efdd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-MHcYV-gtdyEKjSE4znJs_PRsa-eWmA',
    appId: '1:916915644318:ios:eb3d7bb8ade04124a8588f',
    messagingSenderId: '916915644318',
    projectId: 'ecommerce-app-3efdd',
    storageBucket: 'ecommerce-app-3efdd.appspot.com',
    androidClientId: '916915644318-fg5sqsoc7rjomkcarbtpsppvgc3rqcn0.apps.googleusercontent.com',
    iosClientId: '916915644318-a0oblj8626a8bbudqmtt6061dk3g6g1j.apps.googleusercontent.com',
    iosBundleId: 'live.angeloseby.ecommerceApp',
  );
}
